FROM node:16-slim

COPY package*.json .

RUN npm install

COPY . .

EXPOSE 9000

RUN apt update && \
    apt install -y wget netcat && \
    wget -q -O /usr/bin/wait-for https://raw.githubusercontent.com/eficode/wait-for/v2.2.3/wait-for && \
    chmod +x /usr/bin/wait-for

USER node
